site_name: docs-main

theme:
    name: material

nav:
  - Home: index.md
  - Sections:
      - infrastructure:
          - nginx: sections/infrastructure/nginx/index.md
          - docker:
            - sections/infrastructure/docker/files-models.md
            - sections/infrastructure/docker/commands.md
          - ansible:
              - sections/infrastructure/ansible/issues.md

extra_css:
  - css/main.css

markdown_extensions:
  - codehilite
